name: CV Match Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-cv-match:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run CV Match script
        run: |
          python cv_match.py > cv_match_results.txt

      - name: Generate HTML results
        run: |
          python -c "
          import json
          import os
          import re
          
          # Read CV content
          with open('cv_text_example.md', 'r') as f:
              cv_content = f.read()
          
          # Read results
          with open('cv_match_results.txt', 'r') as f:
              results_text = f.read()
          
          # Extract matches
          matches = []
          match_pattern = re.compile(r'(\d+)\. (.+?)\n   Company: (.+?)\n   Location: (.+?)\n   Match score: (.+?)\n   URL: (.+?)\n', re.DOTALL)
          
          for match in match_pattern.finditer(results_text):
              matches.append({
                  'rank': match.group(1),
                  'title': match.group(2),
                  'company': match.group(3),
                  'location': match.group(4),
                  'score': match.group(5),
                  'url': match.group(6)
              })
          
          # Generate HTML
          with open('index.html', 'w') as f:
              f.write(open('cv_match_template.html').read().replace('{{CV_CONTENT}}', cv_content).replace('{{MATCHES_JSON}}', json.dumps(matches)))
          "

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          target-folder: .
          clean: false
          git-config-name: GitHub Actions
          git-config-email: github-actions@github.com
